version: "3.9"
services:
  mysql:
    container_name: mypgs
    image: mypgs
    volumes:
      - ./db.sql:/db.sql
    build:
      context: .
      dockerfile: Dockerfile_db
    environment: 
      - MYSQL_ROOT_PASSWORD=root66
    ports:
      - "3306:3306"
    expose:
      - 3306
  backend:
    container_name: mybak
    image: mybak
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    expose:
      -  9000